### ISSUE TITLE
Feature request: letting users add own parameters

### ISSUE THREAD

**Issue by leggomyinfo** [Fload2000/RemoveLinkTracking#11]
My ideal version of this extension is one where I could add maintain a whitelist and blacklist of parameters in the extension's settings.

Perhaps users could also be prompted upon adding a parameter to the blacklist with the option to notify the extension's author so it can be considered as a global addition.

**Comment by f-str** [comment]
Thanks for this feature request. I thought about this a while ago. The option to enable/disable certain parameters as well as to add new parameters shouldn't be to hard to implement. But it's not so simple to add a way to notify me. Maybe this could be just a banner (which only appears when you added new parameters) with a link to this repository or a mail-to link. Never the less I'll add this to the goals section in the readme.

**Comment by f-str** [comment]
What still needs to be done:
 - [X] Display banner when a new parameter is added
 - [X] Add functionality to remove parameters completely
 - [X] Test if changes in the options last across addon-updates
 - [ ] (Improve CSS #14 )

**Comment by f-str** [comment]
I will close this issue as all functionalities are implemented and will be available in the next version. The only thing is that the CSS design might need a little rework. That's why I have opened a separate issue for this (#14).
