### ISSUE TITLE
Feature request: visual feedback that URL has been altered

### ISSUE THREAD

**Issue by leggomyinfo** [Fload2000/RemoveLinkTracking#12]
I think it would be both helpful & instructive to visually indicate (without being too in-your-face) when a URL has been changed by the extension – perhaps in the web address bar. This provides feedback that the extension is working (and worthwhile) and, if there's an issue with a URL, it's a reminder that the extension may be responsible (i.e. helpful for the user to debug). [This is based on the premise that there will (eventually) be parameters scrubbed which, on rare occasions, may actually serve a user-facing function.]

Food for thought.

**Comment by f-str** [comment]
Thanks for this feature request. That's a pretty nice idea. I think the web address bar could be the right spot for such an indicator icon. But there should be an option to disable/enable this. For the debugging purpose it's maybe cool to show a list of all the removed parameters by clicking on the indicator icon. This will help the user to identify the parameters which maybe break some stuff. I'll add this as well to the goals section in the readme. But it will take some time till this is properly implemented.
