### ISSUE TITLE
breaks Facebook redirects

### ISSUE THREAD

**Issue by leggomyinfo** [Fload2000/RemoveLinkTracking#18]
If I click through a message or notification, I get the equivalent of FB's 404

Here's what appears to be happening:
- click notification icon
- click notification
- URL reloads
- add-on strips something
- original URL loads with "ref" parameter stripped (compared to running with add-on disabled)

I don't know how to capture the URL Facebook is redirecting to for a second to see what parameters are being added & stripped (and consequently breaking the link)

Unfortunately need to whitelist Facebook :(

**Comment by f-str** [comment]
That's a thing which I faced a lot lately, too. For #12 I started to implement some sort of logger, which should log the URL and the removed parameters to help narrow it down what request breaks the site. But this is unfortunately not done yet due to the lack of time on my side.

**Comment by f-str** [comment]
With commit 4b0423d8f7fe14eada451ef807ed3d007cc2e2ea the logging is functional. So it is finally possible to view each URL on which the parameters got removed. It's really not a pretty design, but it should be usable. I think this issue could be closed now. A release with the features will be available in the near future.
