### ISSUE TITLE
alphabetize parameters

### ISSUE THREAD

**Issue by leggomyinfo** [Fload2000/RemoveLinkTracking#19]
I wish the list under details and preferences was alphabetized instead of as follows. It makes it harder to scan the list to see what parameter might be causing an issue.

If a parameter starts with one of the following strings it will be removed:
utm_
wt_
refID
src
ext
_trk
mcID
tt_
eqrecqid
fbclid
yclid
gclid
wc_mc
amp
clickin
AffiliateID
campid
pf_rd
hmb_
igshid
fb
service
algo_
spm
btsid
ws_ab_
action
module
pgtype
cid
sclid
key-sofort_

**Comment by f-str** [comment]
Thanks for the request. This shouldn't be to hard to accomplish.

**Comment by f-str** [comment]
Okay that was a quick one :D 
It will be available in the next release.
I'll close this issue.
