### ISSUE TITLE
clearer direction re. whitelisting

### ISSUE THREAD

**Issue by leggomyinfo** [Fload2000/RemoveLinkTracking#20]
I tried whitelisting "facebook.com" and then "https://www.facebook.com/" – neither worked

It only worked once I put in "www.facebook.com"

It would be helpful if that formatting requirement was surfaced

**Comment by f-str** [comment]
Yeah that's a thing which bothers me too. This definitely needs some work and more description to make it more usable.

**Comment by f-str** [comment]
I think now it is more clear what to enter and how it is functioning. So I will close this issue. The changes will be included in the upcoming release.
