### ISSUE TITLE
Breaks a bank website even after adding "exceptions"

### ISSUE THREAD

**Issue by Ezwen** [Fload2000/RemoveLinkTracking#28]
It has been weeks since I could not log into my (French) bank website, which is: https://www.credit-cooperatif.coop/

I only today found out that the login error that I get disappears when I disable "RemoveLinkTracking" from Firefox.

Happy to finally have found the culprit, I tried adding "exceptions" in the RemoveLinkTracking parameters, and to cover all domains that seem to be used by the website (according to Firefox's debugger):
![Capture d’écran de 2020-09-01 10-56-52](https://user-images.githubusercontent.com/1388961/91829554-e78c9180-ec41-11ea-86b0-232f1ce21c60.png)

Unfortunately the problem remains: I still cannot log into the bank website while RemoveLinkTracking is enabled.

Do you have any idea, by any chance?

Thanks for the nice extension by the way :)

**Comment by f-str** [comment]
One suggestion of mine would be to remove the `https://` of the URLs in the exceptions and retry it.
Another suggestion would be to disable or remove the `action`, `module` and `service` keywords because they break a lot of pages.

**Comment by Ezwen** [comment]
Removing the `https://` did the trick, thanks!

**Comment by f-str** [comment]
Thanks for your feedback.
