### ISSUE TITLE
fbid

### ISSUE THREAD

**Issue by cg00001** [Fload2000/RemoveLinkTracking#3]
Example:
https://www.facebook.com/photo.php?fbid=10157294752732868&set=gm.2373437782884259&type=3&eid=ARDBOCgmaYb5kHA89D_C2b_uU8cl32mxaRUaRpl-V45mI5S4WCNLoph6QDvtuoEJqbXPwNSjgbjlvD0N&ifg=1

**Comment by f-str** [comment]
Thanks for your request!
I edited the keyword 'fb_' to 'fb'. So that your request is considered.
I tested your example link and the parameter was removed.
The updated version will be available soon.
Greetings
