### ISSUE TITLE
Facebook most recent stories fail with extension enabled.

### ISSUE THREAD

**Issue by cg00001** [Fload2000/RemoveLinkTracking#4]
This happens probably because this:
https://www.facebook.com/?ref=tn_tnmn&sk=h_chr

becomes this:
https://www.facebook.com/?sk=h_chr

when the extension is enabled.

**Comment by f-str** [comment]
Thanks for this hint.
For a short term fix I will just remove the 'ref' parameter from the keyword list.
As a long-term solution, however, I will implement the functionality to disable parameters for certain domains.
