### ISSUE TITLE
Facebook Most Recent shows one page and More Posts on the bottom. More Posts button doesn't work with extension on.

### ISSUE THREAD

**Issue by cg00001** [Fload2000/RemoveLinkTracking#5]
The link of the button is (using social fixer as well):
https://www.facebook.com/?ref=tn_tnmn&sk=h_chr#

**Comment by f-str** [comment]
Thanks for this hint.
Can you give a more detailed comment how to reproduce this issue? Does this happen in combination with social fixer or does it happen without too?
Only by looking at the link, I just recognize the `ref` parameter (`sk` was never considered by this add-on). This was removed by the latest update (1.0.4) and shouldn't be considered any more, so please make sure you use that version. Furthermore check if maybe other add-ons may block this feature of Facebook.
Greetings

**Comment by cg00001** [comment]
Uninstalled Remove Link Tracking, installed again and with Social Fixer on -with Most recent enabled on Social Fixer- the home button points to:
https://www.facebook.com/?ref=tn_tnmn&sk=h_chr&sfx_switch=true
Then if you click on More Posts, the link momentarily tries to work but doesn't

Without Social Fixer the home button points to:
https://www.facebook.com/?ref=tn_tnmn

Which works fine.

Here's the interesting bit, without Remove Link Tracking, but with Social Fixer and Most recent enabled the home button points to:
https://www.facebook.com/?ref=tn_tnmn&sk=h_chr

Which works without More Posts button on the end of first page.

Now, here's what I think happens, Social Fixer -when you enable Most recent on it- changes the Home button link from:
https://www.facebook.com/?ref=tn_tnmn
to
https://www.facebook.com/?ref=tn_tnmn&sk=h_chr&sfx_switch=true

Then the More Posts button doesn't work with Remove Link Tracking enabled, the link is:
https://www.facebook.com/?ref=tn_tnmn&sk=h_chr#

The inspector console when pressing the More Posts button says:
storage event 
storage { target: Window, isTrusted: true, key: "x-storage", oldValue: "{\"time\":1568098141415,\"key\":\"options\"}", url: "https://www.facebook.com/?ref=tn_tnmn&sk=h_chr", storageArea: Storage, srcElement: Window, currentTarget: Window, eventPhase: 2, bubbles: false, … }
 error TypeError: "json is null"
    XLib moz-extension://f8356afe-1fa6-4256-9277-d2da3bd69c11/x.js:1424
 json null x.js:1429:14
Load denied by X-Frame-Options: https://www.facebook.com/ajax/pagelet/generic.php/LitestandT…spin_r=1001150254&__spin_b=trunk&__spin_t=1568057441&__adt=6 does not permit framing.

**Comment by f-str** [comment]
Thanks for this explanation.

I was able to reproduce this error.
On the debug console it says the following thing: `Load denied by X-Frame-Options: “DENY” from [...]`

Just to see what parameter is involved in this issue I added `Console.log(param)` after the removing in the `remove.js` script.
The crazy thing is that with just this line added the error is gone and the posts load.
I will do some further investigations why this line fixes it. 

For a short term fix I will just add this line and publish a new version. 
But I will keep this issue open till I get to know whats really going on.
Greetings

**Comment by michael-j-oconnor** [comment]
Hmmm...  I was just playing around with Social Fixer 25.0 with most Recent set + RemoveLinkTracking 1.1.3 and saw the same basic behavior as this closed bug.  "More Posts" doesn't work.  It appears to try, but fails.  The "More Posts" link appears to be:

https://www.facebook.com/?sk=h_chr&sfx_switch=true#

With RemoveLinkTracking, it seems to bomb out with:

"click on A https://www.facebook.com/?sk=h_chr&sfx_switch=true# with URL "undefined" and event undefined"

Perhaps this should be a separate bug, but the outward behavior here seemed identical to my experience.

**Comment by f-str** [comment]
Thanks for your feedback. 
Can you maybe give clear instruction for how to reproduce this error.
I tried to reproduce it, but wasn't able to. To be honest I'm not familiar with the Social Fixer Addon. 
By just looking at the URLs the RemoveLinkTracking addon shouldn't intercept at all (as long as you didn't set custom keywords).
I'm going to reopen this issue till the situation is resolved.
Greetings

**Comment by michael-j-oconnor** [comment]
I just did this with a couple different browser installs now (but same Facebook account).  There were no custom keywords, no changes to RemoveLinkTracking defaults.  I could get more exhaustive if needed, but I _hope_ this will cover enough so you can see the issue for yourself:

1) Install Waterfox Classic 2020.07 (on MacOS, if it matters)
2) Install Social Fixer 25.0 (current).  
3) Log into Facebook.  Look for the wrench in the right hand corner.  Click on that and cllck on "Social Fixer Options" 
4) What I use are General->Most Recent and all the "Hide ..." filters in the Filter tab, to take care of a couple serious annoyances about Facebook.  I hate Facebook, definitely not an expert on that side.  
5) Save Changes

At this point, you shouldn't be seeing "More Posts" much or, if you do, it's very brief until it loads the next content.

Install RemoveLinkTracking, restart browser, go into Facebook and poof -- you should see "More Posts" that you can't go through, as described in the initial bug report.  Yeah, I noticed that nothing of what you filter corresponds to the links that are presented.

**Comment by f-str** [comment]
Ok, I was able to reproduce the issue. But only on the old design of facebook. On the new design the issue seem not to be present.
With the new logging feature of the current dev version I was able to trace down the issue to an ajax request which will be performed when you click on 'More Posts'.
This request URL contains the URL parameter 'fb_dtsg_ag'. This parameter gets deleted by the RemoveLinkTracking addon because it starts with 'fb'.
I think a proper solution for this would be to implement a list with allowed parameters which get not removed, even when they start with one of the disallowed phrases.
Another solution would be to expand #13 to allow certain parameters on certain URLs.

**Comment by michael-j-oconnor** [comment]
Thanks!  Disabling fb as a test works, confirms we're seeing the same thing.  
What are you trying to capture with fb that you don't get with, say, fbclid?  
I could see FB using fb* in general for non-tracking purposes.

**Comment by f-str** [comment]
In #3 was suggested to consider 'fbid' as well. I don't know if this really is used primarily for tracking or for something else. But it doesn't seem to break anything when it gets removed. Maybe I just add 'fbclid' and 'fbid' to the default keywords, remove 'fb' and hopefully we're fine.

**Comment by michael-j-oconnor** [comment]
I'm trying that right now -- delete fb, added fbid.  I noticed that fbclid isn't being stripped in some cases...  not sure if related or not.  Here's an example link, and I confirmed that was the link that is run when I click on it (as distinct from copying the URL).  

https://news.ycombinator.com/item?id=23911700&fbclid=IwAR0fZMPJzLe1FmG0h-t5xQn4LkgZrDR0ChCjXoaJowLy-4E-bI_GL-B8C7s

**Comment by f-str** [comment]
I tried the same thing and couldn't reproduce it. The 'fbclid' parameter always get removed. But if this keep on happening, consider open a separate issue for that matter. 

Concerning the original problem, I am going to remove the 'fb' parameter and add 'fbid' for it in exchange.
